version: "3.5"
services:
  api:
    container_name: api
    build: .
    image: api
    working_dir: /home/node/app
    user: node
    volumes:
      - ./:/home/node/app
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - 4000:4000
  database:
    container_name: db
    image: postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
  database:
